In [2]:
import numpy as np

In [3]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


In [4]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


In [7]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [8]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [11]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
np.random.rand(5)

array([0.35814286, 0.0452437 , 0.3095644 , 0.63678612, 0.68072562])

In [13]:
np.random.rand(5, 5)

array([[0.32423633, 0.70025   , 0.99747172, 0.91109598, 0.93003554],
       [0.84101642, 0.87993873, 0.94210327, 0.80935532, 0.92930662],
       [0.7279691 , 0.63461971, 0.92852947, 0.55081429, 0.17236035],
       [0.2362865 , 0.50846015, 0.27016388, 0.32495878, 0.52963235],
       [0.96925065, 0.13533137, 0.85514551, 0.85114145, 0.97455495]])

In [14]:
np.random.randn(4, 4)

array([[ 0.98101055, -0.1803107 , -0.66056689,  0.65349928],
       [-0.23525573, -1.34610202, -0.30647061,  0.59923943],
       [ 0.52149854,  0.4535758 , -0.95756074, -2.08358566],
       [ 0.5765388 , -0.76513653, -0.73062355, -1.50129304]])

In [15]:
np.random.randint(1, 100, (5, 5))

array([[39, 61,  5,  6,  6],
       [58, 64, 70, 16, 15],
       [34, 57, 49, 66, 17],
       [63, 20, 50,  8,  1],
       [43, 57, 75, 96, 63]])

In [16]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([45, 95, 17, 20, 84, 47, 38, 76, 22, 22, 43, 92, 22, 61, 30, 32, 87,
       72, 57, 17, 60, 70, 93, 98, 54, 45, 96, 30, 16, 32, 42, 56, 12, 21,
       71, 43, 28, 12, 46, 37, 69, 58, 14, 99, 51, 72, 16, 54, 93, 49, 26,
       27, 60, 38, 20, 70])

In [17]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[45, 95, 17, 20, 84, 47, 38],
       [76, 22, 22, 43, 92, 22, 61],
       [30, 32, 87, 72, 57, 17, 60],
       [70, 93, 98, 54, 45, 96, 30],
       [16, 32, 42, 56, 12, 21, 71],
       [43, 28, 12, 46, 37, 69, 58],
       [14, 99, 51, 72, 16, 54, 93],
       [49, 26, 27, 60, 38, 20, 70]])

In [18]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[45, 76, 30, 70, 16, 43, 14, 49],
       [95, 22, 32, 93, 32, 28, 99, 26],
       [17, 22, 87, 98, 42, 12, 51, 27],
       [20, 43, 72, 54, 56, 46, 72, 60],
       [84, 92, 57, 45, 12, 37, 16, 38],
       [47, 22, 17, 96, 21, 69, 54, 20],
       [38, 61, 60, 30, 71, 58, 93, 70]])

In [19]:
betko7x8.reshape(56)

array([45, 76, 30, 70, 16, 43, 14, 49, 95, 22, 32, 93, 32, 28, 99, 26, 17,
       22, 87, 98, 42, 12, 51, 27, 20, 43, 72, 54, 56, 46, 72, 60, 84, 92,
       57, 45, 12, 37, 16, 38, 47, 22, 17, 96, 21, 69, 54, 20, 38, 61, 60,
       30, 71, 58, 93, 70])

In [20]:
daug_betko = np.random.randn(1000, 1000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

585556:-4.934940510937295, 324558:4.787170968313152


In [21]:
print(daug_betko.shape, daug_betko.dtype)

(1000, 1000) float64


In [22]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[5 2 7 1 4 5 7 2 8 9]
5 1 [5 7 2 8]


In [23]:
print(betko10[::-1])

[9 8 2 7 5 4 1 7 2 5]


In [24]:
print(betko10[-3:5:-1])

[2 7]


In [25]:
betko10[::2] = 0
print(betko10)

[0 2 0 1 0 5 0 2 0 9]


In [26]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[45 76 30 70 16 43 14]
 [95 22 32 93 32 28 99]
 [17 22 87 98 42 12 51]
 [20 43 72 54 56 46 72]
 [84 92 57 45 12 37 16]
 [47 22 17 96 21 69 54]
 [38 61 60 30 71 58 93]] (7, 7) 54


In [27]:
print(betko7x7[2:5, 2:5])

[[87 98 42]
 [72 54 56]
 [57 45 12]]


In [28]:
senukai = betko7x7 >= 50
print(senukai)

[[False  True False  True False False False]
 [ True False False  True False False  True]
 [False False  True  True False False  True]
 [False False  True  True  True False  True]
 [ True  True  True False False False False]
 [False False False  True False  True  True]
 [False  True  True False  True  True  True]]


In [29]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[76 70 95 93 99 87 98 51 72 54 56 72 84 92 57 96 69 54 61 60 71 58 93] (23,)


In [30]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([45, 30, 16, 43, 14, 22, 32, 32, 28, 17, 22, 42, 12, 20, 43, 46, 45,
        12, 37, 16, 47, 22, 17, 21, 38, 30]),
 (26,))

In [31]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[45 76 30 70 16 43 14]
 [95 22 32 93 32 28 99]
 [17 22 77 77 77 12 51]
 [20 43 77 77 77 46 72]
 [84 92 77 77 77 37 16]
 [47 22 17 96 21 69 54]
 [38 61 60 30 71 58 93]]


In [32]:
betko8x7

array([[45, 95, 17, 20, 84, 47, 38],
       [76, 22, 22, 43, 92, 22, 61],
       [30, 32, 77, 77, 77, 17, 60],
       [70, 93, 77, 77, 77, 96, 30],
       [16, 32, 77, 77, 77, 21, 71],
       [43, 28, 12, 46, 37, 69, 58],
       [14, 99, 51, 72, 16, 54, 93],
       [49, 26, 27, 60, 38, 20, 70]])

In [33]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [34]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[45, 76, 30, 70, 16, 43, 14, 49],
       [95, 22, 32, 93, 32, 28, 99, 26],
       [17, 22, 91, 54, 90, 12, 51, 27],
       [20, 43, 80, 94, 96, 46, 72, 60],
       [84, 92, 20, 51, 25, 37, 16, 38],
       [47, 22, 17, 96, 21, 69, 54, 20],
       [38, 61, 60, 30, 71, 58, 93, 70]])

In [35]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

# Matematika

In [36]:
simtukai = septyni7 + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [37]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [38]:
simtukai + septyni7

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [39]:
simtukai / septyni7

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [40]:
random77 = betko7x7 ** np.random.randint(2, 10, (7, 7))
random77[:, :3]

array([[       2025, -1692336128, -1029996288],
       [-1165429921, -1800609408,        1024],
       [       4913,       10648,   933568969],
       [ 1280000000,  1594265185,        6400],
       [-1685635072,      778688,        8000],
       [       2209, -1800609408,         289],
       [-1284030912,   -19233191,   777600000]])