In [23]:
print(betko10[::-1])

[2 3 1 5 3 9 2 9 3 1]


In [24]:
print(betko10[-3:5:-1])

[1 5]


In [25]:
betko10[::2] = 0
print(betko10)

[0 3 0 2 0 3 0 1 0 2]


In [26]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[41 37 51 71 86 20 39]
 [74 89 86 30 94 65 29]
 [97 96 24 23 78 47 11]
 [29 52 74 72 94 34 99]
 [19 34 91 62 59 50 30]
 [87 97 18 24 76 53 33]
 [99 20 28 73 57 57 64]] (7, 7) 72


In [27]:
print(betko7x7[2:5, 2:5])

[[24 23 78]
 [74 72 94]
 [91 62 59]]


In [29]:
senukai = betko7x7 >= 50
print(senukai)

[[False False  True  True  True False False]
 [ True  True  True False  True  True False]
 [ True  True False False  True False False]
 [False  True  True  True  True False  True]
 [False False  True  True  True  True False]
 [ True  True False False  True  True False]
 [ True False False  True  True  True  True]]


In [30]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[51 71 86 74 89 86 94 65 97 96 78 52 74 72 94 99 91 62 59 50 87 97 76 53
 99 73 57 57 64] (29,)


In [31]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([41, 37, 20, 39, 30, 29, 24, 23, 47, 11, 29, 34, 19, 34, 30, 18, 24,
        33, 20, 28]),
 (20,))

In [32]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[41 37 51 71 86 20 39]
 [74 89 86 30 94 65 29]
 [97 96 77 77 77 47 11]
 [29 52 77 77 77 34 99]
 [19 34 77 77 77 50 30]
 [87 97 18 24 76 53 33]
 [99 20 28 73 57 57 64]]


In [33]:
betko8x7

array([[41, 74, 97, 29, 19, 87, 99],
       [37, 89, 96, 52, 34, 97, 20],
       [51, 86, 77, 77, 77, 18, 28],
       [71, 30, 77, 77, 77, 24, 73],
       [86, 94, 77, 77, 77, 76, 57],
       [20, 65, 47, 34, 50, 53, 57],
       [39, 29, 11, 99, 30, 33, 64],
       [38, 84, 35, 60, 55, 18, 78]])

In [34]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [35]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[41, 37, 51, 71, 86, 20, 39, 38],
       [74, 89, 86, 30, 94, 65, 29, 84],
       [97, 96, 75, 49, 12, 47, 11, 35],
       [29, 52, 48, 99, 26, 34, 99, 60],
       [19, 34, 27, 54, 42, 50, 30, 55],
       [87, 97, 18, 24, 76, 53, 33, 18],
       [99, 20, 28, 73, 57, 57, 64, 78]])

In [36]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

# Matematika

In [37]:
simtukai = septyni7 + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [38]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [39]:
simtukai + septyni7

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [40]:
simtukai / septyni7

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [41]:
random77 = betko7x7 ** np.random.randint(2, 10, (7, 7))
random77[:, :3]

array([[  581025857,        1369,   416418617],
       [  817792640,    62742241,  -747843200],
       [   -2594335,  1073741824,      421875],
       [-1253550019,     7311616,   254803968],
       [  565150579,  -912490240,   387420489],
       [  962091543,    -2594335, -1864941312],
       [  919965907,     3200000,   481890304]])