# NumPy

* NumPy yra tiesinės algebros biblioteka. Jos pagrindu sukurtos beveik visos su duomenų mokslu susijusios bibliotekos, tokios kaip Pandas ir kt. Numpy procedūriškai yra itin greita, nes yra susieta ryšiais (`bindings`) su C kalba parašytais moduliais. 

* Standartiškai įsidiegia `*pip install numpy*`, jeigu naudojate Anaconda - `*conda install numpy*`

* Papildomai rekomenduojama suinstaliuioti `seaborn`:

`pip install seaborn`

`Seaborn` suinstaliuoja visus reikiamus komponentus, kurie bus reikalingi ateityje, besimokant kurso medžiagą (`pandas`, `pillow`, `matplotlib` ir pan.).

* Dažniausiai naudojamas NumPy ingredientas - NumPy masyvai, arba kitaip dar gali būti vadinami `kitokie sąrašai` (`numpy array`). Jie būna dviejų tipų - vektoriai ir matricos.

Prieš pradedant darbą su NumPy, reikia jį importuoti.

In [37]:
import numpy as np

Tarkime, turime paprastą Python list'ą:

In [3]:
listas = [1, 2, 3, 4, 5]

Paverskime jį į NumPy array:

In [4]:
arr = np.array(listas)

In [5]:
arr

array([1, 2, 3, 4, 5])

Gauname 1 lygio NumPy masyvą (vektorių). Jeigu norime matricos, turime sukurti keletą masyvų masyve:

In [6]:
mano_listai = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matrica = np.array(mano_listai)


In [7]:
matrica

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Masyvas gali būti tiek vektorius, tiek ir matrica.<br>
Dar vienas pavyzdys:

In [8]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Darom matricą:

In [9]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


NumPy trumpinys `np` pripažintas visame pasaulyje ir yra naudotinas.

In [10]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


NumPy turi ir integruotus, paprastus būdus susikurti masyvą. Skliausteliuose reikia įrašyti start, stop ir step(nebūtina) reikšmes:

In [11]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Naudojant `NumPy` biblioteką ir jos funkciją `arange` sukuriamas masyvas, kuris prasideda nuo 5 ir baigiasi prieš 202, su žingsniu 5. Tai reiškia, kad masyvas bus sukurtas su visais skaičiais nuo 5 iki 202 (neįskaitant), kurie yra padalinti iš 5 be liekanos:

In [12]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


Jeigu reikia vektoriaus iš nulių:

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

`np.zeros` gražina sąrašą `array` užpildytą nuliais, kiek nulių paprašysime, tiek nulių duos:

In [14]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


Jeigu reikia matricos iš nulių:

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Dar vienas pavyzdys,kurio metu argumentą `np.zeros` galime paprašyti, kad gražintų matricą.<br>
Argumentą nusirodome kaip `tuple`:

In [16]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Analogiškai veikia `np.ones` metodas.

In [17]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Dar viena naudinga funkcija - `linspace`.<br>
Ji grąžina masyvą, su lygiais intervalais išdėliotomis reikšmėmis. Reikia nurodyti start, stop ir intervalo reikšmes:

In [18]:
np.linspace(1, 11, 3)

array([ 1.,  6., 11.])

In [19]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [20]:
np.linspace(0,20,16)

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ,
       13.33333333, 14.66666667, 16.        , 17.33333333, 18.66666667,
       20.        ])

Jeigu prireikė vienetinės matricos, siekiant sulyginti vieną sąrašą su kitu, naudojam `np.eye` matricą:

In [21]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Random arrays kūrimas

Pirmas metodas susikurti random array - `np.random.rand()`.<br>
Jo pagalba galime susikurti masyvą su atsitiktinėm reikšmėm nuo 0 iki 1 `("uniform" distribution)`

In [23]:
np.random.rand(5)

array([0.7723286 , 0.01713925, 0.09459537, 0.33084533, 0.44487261])

In [24]:
np.random.rand(10)

array([0.30158572, 0.30263171, 0.51581361, 0.53721076, 0.15767624,
       0.46217284, 0.54929303, 0.41941638, 0.22811891, 0.64989452])

jeigu norime ne vektoriaus, o matricos:

In [25]:
np.random.rand(5, 5)

array([[0.13518092, 0.82131211, 0.72665544, 0.41679563, 0.65726253],
       [0.21290002, 0.05230241, 0.13377671, 0.80973482, 0.12208156],
       [0.92573555, 0.33082448, 0.19161104, 0.06898845, 0.78492683],
       [0.73067185, 0.45420944, 0.7227671 , 0.89872776, 0.51883856],
       [0.94719875, 0.30850354, 0.59731914, 0.89886836, 0.56121501]])

In [26]:
np.random.randn(4, 4)

array([[-0.8218907 ,  0.45112826,  0.06829474, -1.08079988],
       [ 0.96894757,  0.90817251,  1.75709377,  1.2831579 ],
       [ 0.44866643, -0.80386952,  1.31153513, -1.2466564 ],
       [ 0.88211617,  2.03609488, -1.15943365, -0.06382593]])

`np.random.randn()` sugeneruos reikšmes iš  `“standard normal” distribution` (standartinis normalusis skirstinys)

In [27]:
np.random.randn(3, 3)

array([[ 0.83028751, -3.81683791,  0.49088776],
       [ 0.03808058,  1.05873003, -0.86379169],
       [ 0.05008541,  1.20582662, -0.28912768]])

`np.random.randint()` sugeneruoja atsitiktines integer reikšmes. Parametruose reikia nurodyti, žemiausią, aukščiausią (neįskaitant) reikšmes ir norimą kiekį reikšmių.

In [28]:
np.random.randint(100, 200, 20)

array([180, 149, 116, 117, 148, 110, 150, 182, 110, 117, 160, 123, 159,
       171, 139, 165, 197, 140, 157, 106])

In [29]:
np.random.randint(1, 100, (5, 5))

array([[ 9, 68, 89, 32, 78],
       [83,  9, 72, 52, 36],
       [30, 63, 47, 65, 81],
       [87, 38, 19, 85, 68],
       [ 7, 16, 11, 13, 11]])

# Masyvų pertvarkymas

`reshape()` metodas leidžia mums performuoti turimą masyvą į kitą formą:

In [30]:
my_array = np.random.randint(0, 100, 64)

In [31]:
my_array

array([ 8, 38,  1, 38, 69, 18, 25, 44, 21, 17, 99, 70, 79, 66, 36, 50, 69,
       28, 88, 55, 65, 94, 66, 93, 54, 15, 10, 27, 22, 61,  2, 86,  1, 31,
        6,  3, 97, 66, 96, 55, 45, 19,  0, 62, 93, 98,  0, 53, 67, 28, 15,
       21, 76, 52, 17, 70, 42, 29, 65, 39, 31, 86, 90, 26])

In [32]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([37, 66, 88, 50, 23, 59, 68, 74, 37, 58, 10, 73, 45, 52, 38, 33, 52,
       83, 31, 26, 51, 49, 64, 83, 13, 58, 55, 12, 72, 46, 36, 13, 47, 45,
       14, 47, 59, 90, 60, 51, 18, 58, 22, 48, 95, 45, 23, 67, 83, 81, 38,
       83, 32, 35, 68, 58])

In [33]:
reshaped_array = my_array.reshape(8, 8)

In [34]:
reshaped_array

array([[ 8, 38,  1, 38, 69, 18, 25, 44],
       [21, 17, 99, 70, 79, 66, 36, 50],
       [69, 28, 88, 55, 65, 94, 66, 93],
       [54, 15, 10, 27, 22, 61,  2, 86],
       [ 1, 31,  6,  3, 97, 66, 96, 55],
       [45, 19,  0, 62, 93, 98,  0, 53],
       [67, 28, 15, 21, 76, 52, 17, 70],
       [42, 29, 65, 39, 31, 86, 90, 26]])

šiame pavyzdyje vektorių iš 64 reikšmių performavome į 8x8 matricą.

In [39]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[37, 66, 88, 50, 23, 59, 68],
       [74, 37, 58, 10, 73, 45, 52],
       [38, 33, 52, 83, 31, 26, 51],
       [49, 64, 83, 13, 58, 55, 12],
       [72, 46, 36, 13, 47, 45, 14],
       [47, 59, 90, 60, 51, 18, 58],
       [22, 48, 95, 45, 23, 67, 83],
       [81, 38, 83, 32, 35, 68, 58]])

In [ ]:
betko8x8 = betko64.reshape(8, 8)
betko8x8

NameError: name 'betko64' is not defined

In [44]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[37, 74, 38, 49, 72, 47, 22, 81],
       [66, 37, 33, 64, 46, 59, 48, 38],
       [88, 58, 52, 83, 36, 90, 95, 83],
       [50, 10, 83, 13, 13, 60, 45, 32],
       [23, 73, 31, 58, 47, 51, 23, 35],
       [59, 45, 26, 55, 45, 18, 67, 68],
       [68, 52, 51, 12, 14, 58, 83, 58]])

In [43]:
betko7x8.reshape(56)

array([37, 74, 38, 49, 72, 47, 22, 81, 66, 37, 33, 64, 46, 59, 48, 38, 88,
       58, 52, 83, 36, 90, 95, 83, 50, 10, 83, 13, 13, 60, 45, 32, 23, 73,
       31, 58, 47, 51, 23, 35, 59, 45, 26, 55, 45, 18, 67, 68, 68, 52, 51,
       12, 14, 58, 83, 58])

# Naudingi Metodai

In [48]:
daug_betko = np.random.randn(1000, 1000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

466921:-4.898007426993453, 977406:4.618240236974853


`max()` ir `.min()` metodai ištraukia maksimalią ir minimalią reikšmes iš masyvo:

In [49]:
my_array.min()

0

In [50]:
my_array.max()

99

In [51]:
print(daug_betko.shape, daug_betko.dtype)

(1000, 1000) float64


## Indeksacija ir reikšmių traukimas

In [52]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[1 3 8 1 3 9 1 3 4 9]
1 1 [9 1 3 4]


`argmax()` ir `argmin()` nurodo mums maksimalios ir minimalios reikšmių indeksą:

In [ ]:
my_array.argmax()

In [ ]:
my_array.argmin()

**.shape** nurodo, kokią formą turi mūsų masyvas:

In [ ]:
reshaped_array.shape

**.dtype** nurodo, koks duomenų tipas yra mūsų masyve:

In [ ]:
reshaped_array.dtype

# Indeksacija ir reikšmių traukimas

In [ ]:
sample_array = np.arange(1,10)

In [ ]:
sample_array

reikšmę iš vektoriaus traukiame taip pat kaip ir iš Python sąrašo:

In [ ]:
sample_array[5]

galime naudoti *slices*:

In [ ]:
sample_array[2:8]

In [ ]:
sample_array[6:]

In [ ]:
sample_array[-5:]

galime pasirinktam rėžiui suteikti kokią nors savo reikšmę *(Broadcasting)*: 

In [ ]:
sample_array[4:8] = 50

In [ ]:
sample_array

# Reikšmių traukimas iš matricos 

In [ ]:
sample = np.random.randint(1, 10, 25)

In [ ]:
sample_matrix = sample.reshape(5,5)

In [ ]:
sample_matrix

In [ ]:
sample_matrix[2,2] 

laužtiniuose skliausteliuose pirmiau nurodome eilutę, paskui tos eilutės nario indeksą.

taip pat galime naudoti rėžius:

In [ ]:
sample_matrix[1:4, 1:4]

In [ ]:
sample_matrix[3:,:]

In [ ]:
sample_matrix[:, 0:2]

# Reikšmių traukimas pagal sąlygą

Tarkime, turime masyvą:

In [ ]:
masyvas = np.arange(1,21)

In [ ]:
masyvas

norime reikšmių, didesnių už 9:

In [ ]:
bool_masyvas = masyvas > 9

In [ ]:
bool_masyvas

gauname masyvą iš *bool* reikšmių, kuriame True reikšmės atitinka užduotą sąlygą. Atlikime tokią operaciją:

In [ ]:
masyvas[bool_masyvas]

kintamojo *masvas* laužtiniuose skliautuose įvedę kintamąjį *bool_masyvas*, gauname reikšmes, kurios atitinka True indeksą. Tą patį rezultatą galime gauti laužtiniuose skliaustuose tiesiog įrašę sąlygą:

In [ ]:
masyvas[masyvas>9]

# Numpy elgsenos ypatumai

Yra tam tikri NumPy elgsenos ypatumai, tarkime:

In [ ]:
pvz = np.random.randint(1, 21, 20)

In [ ]:
pvz

turime *random* masyvą iš integer reikšmių. Susikurkime jo atraižą:

In [ ]:
pvz_ispjova = pvz[5:15]

In [ ]:
pvz_ispjova

In [ ]:
pvz_ispjova[:] = 99

In [ ]:
pvz_ispjova

Iki šio momento viskas atrodo kaip ir tikėtąsi. Tačiau išsikvietę pirmąjį masyvą matome:

In [ ]:
pvz

Paprastai kuriant kintamąjį, užkulisiuose padaroma kopija šaltinio, iš kurio jis gaminamas (šiuo atveju *pvz*). 
Iš tos kopijos formuojamas naujas kintamasis. Tačiau NumPy atveju pakeitimai vykdomi originale, ir mums 
rodoma tik modifikuota to originalo dalis. NumPy pritaikytas darbui su milžiniškais kiekiais duomenų. Daryti laikinas jų kopijas atmintyje yra neefektyvu, ir nestabilu. Todėl, kai norime išsaugoti originalą, turime nurodyti, kad norėsime pasidaryti kopiją:

In [ ]:
pvz_copy = pvz.copy()

In [ ]:
pvz_copy

In [ ]:
pvz_copy == pvz

In [ ]:
pvz_copy_ispjova = pvz_copy[5:15]
pvz_copy_ispjova[:] = 100

In [ ]:
pvz_copy_ispjova

In [ ]:
pvz

In [ ]:
pvz_copy

Taigi, pasidarėme kopiją, nurodėme kad norime jos rėžio [5:15] kintamąjame *pvz_copy_ispjova*, joje visas reikšmes pakeitėme į 100, ir įsitikinome, kad po to originalusis *pvz* liko nepakeistas.

# Matematinės operacijos ir funkcijos

su NumPy arrays galima atlikti paprastus aritmetinius veiksmus:

In [ ]:
vektorius = np.arange(1,11)

In [ ]:
vektorius

In [ ]:
vektorius + vektorius

In [ ]:
vektorius * vektorius

In [ ]:
vektorius / vektorius

In [ ]:
vektorius / 0

atkreipkite dėmesį, atlikus dalybą iš 0 gausime begalybes arba nan - not a number. Taip pat galime atlikti veiksmus ir su skaičiais:

In [ ]:
vektorius + 1000

In [ ]:
vektorius ** 3

ir t.t.

Numpy aplinkoje taip pat galime taikyti įvairias trigonometrines funkcijas ir tt.

In [ ]:
np.sin(vektorius)

In [ ]:
np.log(vektorius)

Visas matematines funkcijas galite surasti
[čia](https://docs.scipy.org/doc/numpy/reference/ufuncs.html).